# From here below is the manual hyprland.conf file

#--- PROGRAMS ---#

$terminal = ghostty
$browser = firefox
$launcher = rofi -show drun
$runner = $SHELL -c "$(rofi -dmenu -p '' -l 0)"
$screenshot = grimblast copysave area
$swayosd = swayosd-client --monitor "$(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')"

#---  BINDS   ---#

$mainMod = SUPER

bind = $mainMod, Return, exec, uwsm app -- $terminal
bind = $mainMod, C, exec, uwsm app -- $browser
bind = $mainMod, Space, exec, $launcher
bind = CTRL+$mainMod, Space, exec, $runner
bind = , Print, exec, $screenshot

bind = CTRL+$mainMod, left, movecurrentworkspacetomonitor, -1
bind = CTRL+$mainMod, right, movecurrentworkspacetomonitor, +1

bind = CTRLALT, Delete, exec, uwsm stop
bind = $mainMod, Q, killactive
bind = $mainMod, F, fullscreen
bind = $mainMod, Z, togglefloating

# TODO: pseudo/togglesplit binds

# OSD binds
bindel = ,XF86AudioRaiseVolume, exec, $swayosd --output-volume +5 --max-volume 150
bindel = ,XF86AudioLowerVolume, exec, $swayosd --output-volume -5 --max-volume 150
bindel = ,XF86AudioMute, exec, $swayosd --output-volume mute-toggle
bindel = ,XF86AudioMicMute, exec, $swayosd --input-volume mute-toggle
bindel = ,XF86MonBrightnessUp, exec, $swayosd --brightness +10
bindel = ,XF86MonBrightnessDown, exec, $swayosd --brightness -10

#--- SETTINGS ---#

xwayland {
	force_zero_scaling = true
}

general {
	gaps_in = 0
	gaps_out = 0
}

decoration {
	rounding = 0
}

misc {
	enable_anr_dialog = false
	close_special_on_empty = false
	new_window_takes_over_fullscreen = 2
}

#--- AUTOSTART --#

exec-once = hyprpaper
exec-once = mako
exec-once = hyprpolkitagent
exec-once = swayosd-libinput-backend
exec-once = swayosd-server

#---   RULES  ---#

windowrulev2 = tag +game, class:ffxiv_dx11.exe
windowrulev2 = tag +game, class:osu!

windowrulev2 = opacity 1 override, tag:game
windowrulev2 = opacity 1 override, class:firefox, fullscreen:1

#--- SOURCES  ---#

source = ~/.config/hypr/original.conf

