# Edit this justfile per installation

# Nix setup
flake := "<PATH-TO-FLAKE>"
machine := "<MACHINE-NAME>"

# Disks setup
disk := "<NAME-OF-DISK>"
bootPartition := disk + "1"
mainPartition := disk + "2"
swapSize := "<SIZE-IN-GB>"

# Commands

# Display all possible targets
help:
	@just --list --justfile {{justfile()}}

# Print out the current variables
debug:
	@echo "flake = {{flake}}"
	@echo "machine = {{machine}}"
	@echo "disk = {{disk}}"
	@echo "bootPartition = {{bootPartition}}"
	@echo "mainPartition = {{mainPartition}}"

# Partition creation
cfdisk:
	@cfdisk {{disk}}

# Basic filesystem creation
fs:
	just fsBoot
	just fsMain
	just mount
	just swap

# Boot filesystem creation
fsBoot:
	@sudo mkfs.fat -F 32 {{bootPartition}}
	@sudo fatlabel {{bootPartition}} NIXBOOT

# Main filesystem creation
fsMain:
	@sudo mkfs.btrfs {{mainPartition}} -L NIXOS

# Mount partitions
mount flags:
	@sudo mount /dev/disk/by-label/NIXOS /mnt -o {{flags}}
	@sudo mount /dev/disk/by-label/NIXBOOT /mnt/boot --mkdir

# Create swap file
swap:
	@sudo btrfs filesystem mkswapfile --size {{swapSize}}g --uuid clear /mnt/.swapfile
	@sudo swapon /mnt/.swapfile

# Generate config
generate flags:
	@sudo nixos-generate-config {{flags}} --root /mnt

# Generate config without filesystems
nohw:
	@just generate --no-filesystems

# disko-install
# mutually exclusive to manual filesystem setup
# ONLY USE THIS OPTION IF YOU WANT TO WIPE THE ENTIRE DISK
[doc("disko-install (read comments)")]
disko:
	@sudo disko-install -- --write-efi-boot-entries --flake {{flake}}#{{machine}} --disk main {{disk}}

# Install the system
# Remember to run passwd after installation
[doc("Install the system (read comments)")]
install:
	@cd /mnt
	@sudo nixos-install
